<a href="https://colab.research.google.com/github/Srishtik-ui/Traning_program_of_ml-colud_security/blob/main/Workshop_day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import random
import math

heights = [random.randint(150,190) for i in range(20)]
print("Sample height (cm):", heights)
#snd
#mean nd sd
mean = sum(heights)/len(heights)
variance = sum([(i-mean)**2 for i in heights])/len(heights)
sd = math.sqrt(variance)
print("Standard deviation:", sd)
print("Mean height (cm):", mean)

Sample height (cm): [153, 156, 157, 174, 159, 156, 160, 182, 181, 158, 174, 188, 182, 167, 186, 161, 174, 154, 153, 187]
Standard deviation: 12.457527844640765
Mean height (cm): 168.1


In [ ]:
import random
import math

random.seed(43)
heights = [random.randint(150,190) for i in range(20)]
print("Original sample heights (cm):", heights)


heights.insert(0, 1000)
print("Sample heights with outliers (cm):", heights)

mean = sum(heights)/len(heights)
variance = sum([(i-mean)**2 for i in heights])/len(heights)
sd = math.sqrt(variance)
print("\nStandard deviation with outliers:", sd)
print("Mean height with outliers (cm):", mean)


Z_score_first_element = (heights[0]-mean)/sd
print("\nFirst element height:", heights[0])
print("Z_score for first element:", Z_score_first_element)

z_scores = [(h - mean) / sd for h in heights]
print("\nZ-scores for all heights:", z_scores)

outlier_value_1000 = 1000

Original sample heights (cm): [152, 168, 159, 179, 173, 156, 179, 188, 181, 188, 151, 182, 177, 186, 173, 189, 185, 177, 175, 161]
Sample heights with outliers (cm): [1000, 152, 168, 159, 179, 173, 156, 179, 188, 181, 188, 151, 182, 177, 186, 173, 189, 185, 177, 175, 161]

Standard deviation with outliers: 176.29767652552692
Mean height with outliers (cm): 213.28571428571428

First element height: 1000
Z_score for first element: 4.462420045566363

Z-scores for all heights: [4.462420045566363, -0.34762633004321214, -0.25687073805057864, -0.307920758546435, -0.19447626855564315, -0.22850961555288068, -0.32493743204505376, -0.19447626855564315, -0.1434262480597868, -0.18313181955656396, -0.1434262480597868, -0.3532985545427517, -0.17745959505702436, -0.20582071755472234, -0.15477069705886598, -0.22850961555288068, -0.1377540235602472, -0.1604429215584056, -0.20582071755472234, -0.21716516655380153, -0.2965763095473558]


In [ ]:
import numpy as np
data_list = [1,2,3]

try:

    data_list = data_list +10
except TypeError :
  print("Lists require loops: ", [x+10 for x in data_list])

data_np = np.array([1,2,3])

print("Numpy vectorized addition : ", data_np +10)

Lists require loops:  [11, 12, 13]
Numpy vectorized addition :  [11 12 13]


In [ ]:
import sys

size = 1000000
python_list = list(range(size))
numpy_array = np.arange(size)

print(f"List overhead (base):{sys.getsizeof(python_list)} bytes")
print(f"Numpy array overhead (base):{sys.getsizeof(numpy_array)} bytes")

List overhead (base):8000056 bytes
Numpy array overhead (base):8000112 bytes


In [ ]:
import time

size = 1000000
list1 = list(range(size))
list2 = list(range(size))
array1 = np.arange(size)
array2 = np.arange(size)

start = time.time()
result = [x + y for x, y in zip(list1, list2)]
print(f"List addition time: {time.time() - start:.5f}s")

start = time.time()
res_np = array1 + array2
print(f"Numpy array addition time: {time.time() - start:.5f}s")

List addition time: 0.08003s
Numpy array addition time: 0.00397s


In [ ]:
import numpy as np

a = np.array(([1,2],[3,4]))
b = np.array(([5,6,7],[8,9,10]))
print("a",type(a))
print(a)
print("\nb",type(b))
print(b)

#matix as matrix objects
c = np.matrix(([1,2],[3,4]))
d = np.matrix(([5,6,7],[8,9,10]))
print("\nc",type(c))
print(c)
print("\nd",type(d))
print(d)

a <class 'numpy.ndarray'>
[[1 2]
 [3 4]]

b <class 'numpy.ndarray'>
[[ 5  6  7]
 [ 8  9 10]]

c <class 'numpy.matrix'>
[[1 2]
 [3 4]]

d <class 'numpy.matrix'>
[[ 5  6  7]
 [ 8  9 10]]
