<a href="https://colab.research.google.com/github/Srishtik-ui/Traning_program_of_ml-colud_security/blob/main/Workshop_Day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
print("\na",type(a))
print(a)
print("\nb",type(b))
print(b)

#matrix as matrix object

c = np.matrix([[1,2],[3,4]])
d = np.matrix([[5,6],[7,8]])
print("\nc",type(c))
print(c)
print("\nd",type(d))
print(d)
print("\n* operation on two ndarray object (ElementWise)")
print(a * b)
print("\n operation on two matrix object (same as np.dot())")
print(c * d)


a <class 'numpy.ndarray'>
[1 2 3]

b <class 'numpy.ndarray'>
[4 5 6]

c <class 'numpy.matrix'>
[[1 2]
 [3 4]]

d <class 'numpy.matrix'>
[[5 6]
 [7 8]]

* operation on two ndarray object (ElementWise)
[ 4 10 18]

 operation on two matrix object (same as np.dot())
[[19 22]
 [43 50]]


In [ ]:
import numpy as np
a = np.array([[1,2],[3,4],[5,6]])
print("a = ")
print(a)

print("\nWith transpose (a) function")
print(np.transpose(a))

print("\nWith transpose (a.T) attribute")
print(a.T)

print("\nWith ndarray.T attribute")
print(a.T)

a = 
[[1 2]
 [3 4]
 [5 6]]

With transpose (a) function
[[1 3 5]
 [2 4 6]]

With transpose (a.T) attribute
[[1 3 5]
 [2 4 6]]

With ndarray.T attribute
[[1 3 5]
 [2 4 6]]


In [ ]:
import numpy as np
c = np.matrix([[1,2],[5,6]])
det = np.linalg.det(c)
print("Determinent:",det)

Determinent: -3.999999999999999


In [ ]:
import numpy as np

c = np.array([[1,2,3],[4,5,6]])
trace = np.trace(c)
print("Trace:",trace)
print("Trace:",sum(c.diagonal()))

Trace: 6
Trace: 6


In [ ]:
#Rank of matrix
a = np.arange(1,10)
a.shape = (3,3)
print("a = ")
print(a)
print("rank of a = ")
print(np.linalg.matrix_rank(a))

a = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
rank of a = 
2


In [ ]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])


det = A[0,0]*A[1,1] - A[0,1]*A[1,0]

if det == 0:
    print("Inverse does not exist")
else:

    cofactor = np.array([[ A[1,1], -A[0,1]],
                          [-A[1,0],  A[0,0]]])

    adjoint = cofactor.T
    inverse = (1/det) * adjoint

    print("Inverse Matrix:")
    print(inverse)


Inverse Matrix:
[[-2.   1.5]
 [ 1.  -0.5]]


In [ ]:
#pseudo Inverse
a = np.array([[2,8],
 [1,4]])
print("a = ")
print(a)
det = np.linalg.det(a)
print("Determinant:",det)
pinv = np.linalg.pinv(a)
print("\nPseudo Inverse of a = ")
print(pinv)


a = 
[[2 8]
 [1 4]]
Determinant: 0.0

Pseudo Inverse of a = 
[[0.02352941 0.01176471]
 [0.09411765 0.04705882]]


In [ ]:
# Flattening a Matrix
a = np.arange(1,10)
a.shape = (3,3)
print("a = ")
print(a)
print("\nAfter flattening: ")
print(a.flatten())
print("\nAfter reshaping:")
print(a.reshape(-1))

a = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

After flattening: 
[1 2 3 4 5 6 7 8 9]

After reshaping:
[1 2 3 4 5 6 7 8 9]


In [ ]:
import pandas as pd
df = pd.read_csv("/content/1995.csv")
df.info()
print(df.head(10))
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Years    20 non-null     int64 
 1   Product  20 non-null     object
 2   Price    20 non-null     int64 
dtypes: int64(2), object(1)
memory usage: 612.0+ bytes
   Years    Product  Price
0   1995  Fast Food    200
1   1995      Sweet    150
2   1995  Fast Food    100
3   1995  Fast Food    250
4   1995  Fast Food    260
5   1995      Sweet    230
6   1995      Sweet    210
7   1995  Fast Food    120
8   1995      Sweet    150
9   1995  Fast Food    160


(20, 3)

In [ ]:
df.shape

(20, 3)

In [ ]:
data = pd.read_csv("/content/big_mart_sales.csv", delimiter = ',')
print(data)


     Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0              FDA15        9.300          Low Fat         0.016047   
1              DRC01        5.920          Regular         0.019278   
2              FDN15       17.500          Low Fat         0.016760   
3              FDX07       19.200          Regular         0.000000   
4              NCD19        8.930          Low Fat         0.000000   
...              ...          ...              ...              ...   
8518           FDF22        6.865          Low Fat         0.056783   
8519           FDS36        8.380          Regular         0.046982   
8520           NCJ29       10.600          Low Fat         0.035186   
8521           FDN46        7.210          Regular         0.145221   
8522           DRG01       14.800          Low Fat         0.044878   

                  Item_Type  Item_MRP Outlet_Identifier  \
0                     Dairy  249.8092            OUT049   
1               Soft Drinks  

In [ ]:
df2= pd.read_csv("/content/read_data_with_skipping_row.csv")
df2

what are you up to with this data Unnamed: 1 Unnamed: 2
0   This are the things that are related to the pr...        NaN        NaN
1                                                 NaN        NaN        NaN
2                                                 NaN        NaN        NaN
3                                               Years    Product      Price
4                                                1995  Fast Food        200
5                                                1995      Sweet        150
6                                                1995  Fast Food        100
7                                                1995  Fast Food        250
8                                                1995  Fast Food        260
9                                                1995      Sweet        230
10                                               1995      Sweet        210
11                                               1995  Fast Food        120
12                                               1995      Sweet        150
13                                               1995  Fast Food        160
14                                               1995  Fast Food        140
15                                               1995      Sweet        180
16                                               1995  Fast Food        190
17                                               1995      Sweet        130
18                                               1995  Fast Food        123
19                                               1995      Sweet        210
20                                               1995      Sweet        250
21                                               1995  Fast Food        120
22                                               1995      Sweet        159
23                                               1995  Fast Food        160

In [ ]:
#missing row We use (skiprows) function
df2= pd.read_csv("/content/read_data_with_skipping_row.csv",skiprows=4)
df2

Years    Product  Price
0    1995  Fast Food    200
1    1995      Sweet    150
2    1995  Fast Food    100
3    1995  Fast Food    250
4    1995  Fast Food    260
5    1995      Sweet    230
6    1995      Sweet    210
7    1995  Fast Food    120
8    1995      Sweet    150
9    1995  Fast Food    160
10   1995  Fast Food    140
11   1995      Sweet    180
12   1995  Fast Food    190
13   1995      Sweet    130
14   1995  Fast Food    123
15   1995      Sweet    210
16   1995      Sweet    250
17   1995  Fast Food    120
18   1995      Sweet    159
19   1995  Fast Food    160

In [ ]:
import glob
import pandas as pd

file_list = glob.glob("/content/Years/*.csv")



all_data = pd.DataFrame()

for file in file_list:
  df = pd.read_csv(file)
  all_data = pd.concat([all_data,df],ignore_index= False)

print(all_data)
type(all_data)
all_data.head(20)

    Years    Product  Price
0    1995  Fast Food    200
1    1995      Sweet    150
2    1995  Fast Food    100
3    1995  Fast Food    250
4    1995  Fast Food    260
..    ...        ...    ...
15   1997      Sweet    210
16   1997      Sweet    250
17   1997  Fast Food    120
18   1997      Sweet    159
19   1997  Fast Food    160

[80 rows x 3 columns]


Years    Product  Price
0    1995  Fast Food    200
1    1995      Sweet    150
2    1995  Fast Food    100
3    1995  Fast Food    250
4    1995  Fast Food    260
5    1995      Sweet    230
6    1995      Sweet    210
7    1995  Fast Food    120
8    1995      Sweet    150
9    1995  Fast Food    160
10   1995  Fast Food    140
11   1995      Sweet    180
12   1995  Fast Food    190
13   1995      Sweet    130
14   1995  Fast Food    123
15   1995      Sweet    210
16   1995      Sweet    250
17   1995  Fast Food    120
18   1995      Sweet    159
19   1995  Fast Food    160

In [ ]:
all_data.to_csv("/content/merged_data.csv",index=False)


In [ ]:
X = pd.read_csv("/content/merged_data.csv",delimiter = ',')
print(X)

    Years    Product  Price
0    1995  Fast Food    200
1    1995      Sweet    150
2    1995  Fast Food    100
3    1995  Fast Food    250
4    1995  Fast Food    260
..    ...        ...    ...
75   1997      Sweet    210
76   1997      Sweet    250
77   1997  Fast Food    120
78   1997      Sweet    159
79   1997  Fast Food    160

[80 rows x 3 columns]
